export const siteData = [
    {
      id: 1,
      title: "Uniswap",
      description: "A decentralized exchange protocol",
      url: "https://www.uniswap.org",
      category: "DeFi",
    },
    {
      id: 2,
      title: "Yearn Finance",
      description: "A yield aggregator platform",
      url: "https://www.yearn.fi",
      category: "DeFi",
    },
    {
      id: 3,
      title: "Compound",
      description: "A decentralized lending protocol",
      url: "https://www.compound.finance",
      category: "DeFi",
    },
    {
      id: 4,
      title: "Rarity Tools",
      description: "Tools for searching NFT trait rarity and more",
      url: "https://rarity.tools",
      category: "NFT",
    },
    {
      id: 5,
      title: "Gem",
      description: "NFT aggregator",
      url: "https://gem.xyz",
      category: "NFT",
    },
    {
      id: 6,
      title: "OpenSea",
      description: "NFT marketplace",
      url: "https://opensea.io",
      category: "NFT",
    },
    {
      id: 7,
      title: "Icy Tools",
      description: "Real-time market insights, more NFT alpha",
      url: "https://icy.tools",
      category: "NFT",
    },
    {
      id: 8,
      title: "Degenz",
      description: "NFT Data",
      url: "https://www.degenz.finance/",
      category: "NFT",
    },
    {
      id: 9,
      title: "Sudoswap",
      description: "NFT LPing and trading",
      url: "https://www.sudoswap.io/",
      category: "NFT",
    },
    {
      id: 10,
      title: "Dune Analytics",
      description: "A powerful tool for querying and visualizing blockchain data",
      url: "https://dune.xyz",
      category: "Analytics",
    },
    {
      id: 11,
      title: "Flipside Crypto",
      description: "A platform for analyzing and understanding blockchain data",
      url: "https://flipsidecrypto.xyz/",
      category: "Analytics",
    },
    {
      id: 12,
      title: "Glassnode",
      description: "A provider of on-chain data and analytics",
      url: "https://glassnode.com",
      category: "Analytics",
    },
  ];
  